#!/usr/bin/env bash
# Feature: claude
# Installs @anthropic-ai/claude-code globally via npm.
# Auto-bootstraps Node via mise if no Node is present, so the feature works
# standalone (the autogenerated test runs it against a bare base image).
set -euo pipefail

CLAUDE_VERSION="${VERSION:-latest}"

if [ "$(id -u)" -ne 0 ]; then
  echo "claude feature: must run as root" >&2
  exit 1
fi

detect_user() {
  if [ -n "${_REMOTE_USER:-}" ] && id -u "${_REMOTE_USER}" >/dev/null 2>&1; then
    echo "${_REMOTE_USER}"; return
  fi
  for c in vscode node ubuntu devcontainer; do
    if id -u "${c}" >/dev/null 2>&1; then echo "${c}"; return; fi
  done
  echo "root"
}

USERNAME="$(detect_user)"
USER_GROUP="$(id -gn "${USERNAME}")"

# Pick up node from common locations populated by other features.
# shellcheck disable=SC1091
[ -f /etc/profile.d/mise.sh ] && . /etc/profile.d/mise.sh
# shellcheck disable=SC1091
[ -f /etc/profile.d/nvm.sh ]  && . /etc/profile.d/nvm.sh
export PATH="/usr/local/bin:${PATH}"

# --- bootstrap Node via mise if absent --------------------------------------
if ! command -v npm >/dev/null 2>&1; then
  echo "claude feature: no Node detected — bootstrapping Node LTS via mise"
  export DEBIAN_FRONTEND=noninteractive
  apt-get update -y
  apt-get install -y --no-install-recommends ca-certificates curl git build-essential
  apt-get clean
  rm -rf /var/lib/apt/lists/*

  export MISE_DATA_DIR="/usr/local/share/mise"
  install -d -m 0775 "${MISE_DATA_DIR}"

  if ! command -v mise >/dev/null 2>&1; then
    curl -fsSL https://mise.run | MISE_INSTALL_PATH=/usr/local/bin/mise sh
  fi
  mise use --global node@lts
  mise install node@lts

  NODE_BIN_DIR="$(mise where node@lts)/bin"
  for bin in node npm npx corepack; do
    src="${NODE_BIN_DIR}/${bin}"
    [ -x "${src}" ] && ln -sf "${src}" "/usr/local/bin/${bin}"
  done

  chown -R "${USERNAME}:${USER_GROUP}" "${MISE_DATA_DIR}"
  chmod -R a+rwX "${MISE_DATA_DIR}"
  find "${MISE_DATA_DIR}" -type d -exec chmod g+s {} +
fi

if ! command -v npm >/dev/null 2>&1; then
  echo "claude feature: ERROR — npm still not on PATH after bootstrap" >&2
  exit 1
fi

echo "claude feature: using node $(node --version), npm $(npm --version)"

# --- install Claude Code CLI ------------------------------------------------
NPM_SPEC="@anthropic-ai/claude-code"
if [ "${CLAUDE_VERSION}" != "latest" ]; then
  NPM_SPEC="${NPM_SPEC}@${CLAUDE_VERSION}"
fi

npm install -g --no-audit --no-fund "${NPM_SPEC}"

if ! command -v claude >/dev/null 2>&1; then
  echo "claude feature: ERROR — 'claude' command not on PATH after install" >&2
  exit 1
fi

echo "claude feature: installed claude $(claude --version 2>&1 | head -n1 || true)"
echo "claude feature: done"
