#!/usr/bin/env bash
# Feature: claude
# Installs @anthropic-ai/claude-code globally via npm.
# Auto-bootstraps Node via mise if no Node is present, so the feature works
# standalone (the autogenerated test runs it against a bare base image).
set -euo pipefail

CLAUDE_VERSION="${VERSION:-latest}"

if [ "$(id -u)" -ne 0 ]; then
  echo "claude feature: must run as root" >&2
  exit 1
fi

detect_user() {
  if [ -n "${_REMOTE_USER:-}" ] && id -u "${_REMOTE_USER}" >/dev/null 2>&1; then
    echo "${_REMOTE_USER}"; return
  fi
  for c in vscode node ubuntu devcontainer; do
    if id -u "${c}" >/dev/null 2>&1; then echo "${c}"; return; fi
  done
  echo "root"
}

USERNAME="$(detect_user)"
USER_GROUP="$(id -gn "${USERNAME}")"

# Pick up node from common locations populated by other features.
# shellcheck disable=SC1091
[ -f /etc/profile.d/mise.sh ] && . /etc/profile.d/mise.sh
# shellcheck disable=SC1091
[ -f /etc/profile.d/nvm.sh ]  && . /etc/profile.d/nvm.sh
export PATH="/usr/local/bin:${PATH}"

# --- bootstrap Node via mise if absent --------------------------------------
if ! command -v npm >/dev/null 2>&1; then
  echo "claude feature: no Node detected — bootstrapping Node LTS via mise"
  export DEBIAN_FRONTEND=noninteractive
  apt-get update -y
  apt-get install -y --no-install-recommends ca-certificates curl git build-essential
  apt-get clean
  rm -rf /var/lib/apt/lists/*

  export MISE_DATA_DIR="/usr/local/share/mise"
  install -d -m 0775 "${MISE_DATA_DIR}"

  if ! command -v mise >/dev/null 2>&1; then
    curl -fsSL https://mise.run | MISE_INSTALL_PATH=/usr/local/bin/mise sh
  fi

  # System-wide pin so the shim can resolve node version for any user.
  install -d -m 0755 /etc/mise
  if [ ! -f /etc/mise/config.toml ]; then
    printf '[tools]\n' > /etc/mise/config.toml
  fi
  if grep -q '^node = ' /etc/mise/config.toml; then
    sed -i 's|^node = .*|node = "lts"|' /etc/mise/config.toml
  else
    sed -i '/^\[tools\]/a node = "lts"' /etc/mise/config.toml
  fi
  chmod 0644 /etc/mise/config.toml

  mise install node@lts
  mise reshim

  # Use mise shims, not symlinks to the real binary — npm resolves its lib
  # relative to argv[0] and a direct symlink breaks `npm -v`.
  SHIMS_DIR="${MISE_DATA_DIR}/shims"
  cat > /etc/profile.d/mise.sh <<EOF
export MISE_DATA_DIR="${MISE_DATA_DIR}"
export PATH="${SHIMS_DIR}:\$PATH"
EOF
  chmod 0644 /etc/profile.d/mise.sh

  for bin in node npm npx corepack; do
    src="${SHIMS_DIR}/${bin}"
    [ -x "${src}" ] && ln -sf "${src}" "/usr/local/bin/${bin}"
  done

  chown -R "${USERNAME}:${USER_GROUP}" "${MISE_DATA_DIR}"
  chmod -R a+rwX "${MISE_DATA_DIR}"
  find "${MISE_DATA_DIR}" -type d -exec chmod g+s {} +
fi

if ! command -v npm >/dev/null 2>&1; then
  echo "claude feature: ERROR — npm still not on PATH after bootstrap" >&2
  exit 1
fi

echo "claude feature: using node $(node --version), npm $(npm --version)"

# --- install Claude Code CLI ------------------------------------------------
NPM_SPEC="@anthropic-ai/claude-code"
if [ "${CLAUDE_VERSION}" != "latest" ]; then
  NPM_SPEC="${NPM_SPEC}@${CLAUDE_VERSION}"
fi

npm install -g --no-audit --no-fund "${NPM_SPEC}"

# `npm install -g` drops the `claude` bin under the node install's bin dir
# (mise's install dir, or whatever NPM_PREFIX points at). Make sure it shows
# up on PATH for the remote user via mise shims + a /usr/local/bin symlink.
if command -v mise >/dev/null 2>&1; then
  mise reshim || true
fi

# Find the freshly installed binary and symlink it.
CLAUDE_BIN=""
for candidate in \
  "/usr/local/share/mise/shims/claude" \
  "$(npm bin -g 2>/dev/null)/claude" \
  "$(dirname "$(command -v npm)")/claude"; do
  if [ -n "${candidate}" ] && [ -x "${candidate}" ]; then
    CLAUDE_BIN="${candidate}"
    break
  fi
done

if [ -z "${CLAUDE_BIN}" ]; then
  # Last-resort fallback: search mise install dirs.
  CLAUDE_BIN="$(find /usr/local/share/mise/installs -maxdepth 5 -name claude -type f -executable 2>/dev/null | head -n1)"
fi

if [ -z "${CLAUDE_BIN}" ] || [ ! -x "${CLAUDE_BIN}" ]; then
  echo "claude feature: ERROR — 'claude' binary not found after npm install -g" >&2
  echo "npm prefix: $(npm config get prefix 2>&1 || true)" >&2
  exit 1
fi

ln -sf "${CLAUDE_BIN}" /usr/local/bin/claude

if ! command -v claude >/dev/null 2>&1; then
  echo "claude feature: ERROR — 'claude' command not on PATH after symlink (${CLAUDE_BIN})" >&2
  exit 1
fi

echo "claude feature: installed claude $(claude --version 2>&1 | head -n1 || true) at ${CLAUDE_BIN}"
echo "claude feature: done"
